
project_id = "ggbvhsuuwqwjghxpuapg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions]
enabled = true
port = 54328

[functions.detection-logs]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.billing-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false
