
project_id = "ggbvhsuuwqwjghxpuapg"

[functions.get-agora-token]
verify_jwt = true

[functions.get-agora-appid]
verify_jwt = true

[functions.cleanup-rooms]
verify_jwt = true

[functions.nsfw-detections]
verify_jwt = true
