// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggbvhsuuwqwjghxpuapg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnYnZoc3V1d3F3amdoeHB1YXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzk0NzUsImV4cCI6MjA1OTk1NTQ3NX0.6FN9aTICMW6LnNYxag0r-pFuchDazX9ZSInlHTrpS7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);