
name: Release Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build extension
        run: npm run build:ext
        env:
          CLUTSH_API_URL: ${{ secrets.CLUTSH_API_URL }}
          
      - name: Package extension
        run: cd extension/dist && zip -r ../../clutsh-nsfw.zip .
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: clutsh-nsfw
          path: clutsh-nsfw.zip
